apiVersion: apps/v1
kind: Deployment
metadata:
  name: acs-helloworld-{{.Release.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acs-helloworld-{{.Release.Name}}
  template:
    metadata:
      labels:
        app: acs-helloworld-{{.Release.Name}}
    spec:
      containers:
      - name: acs-helloworld-{{.Release.Name}}
        image: 221639781053.dkr.ecr.us-east-1.amazonaws.com/sc-snowflake-service:dev-76
        ports:
        - containerPort: 8094
        env:
        - name: TITLE
          value: {{ .Values.title }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
  selector:
    app: acs-helloworld-{{.Release.Name}}
